name: "Build Armbian"
on:
  workflow_dispatch:
jobs:
  build-armbian:
    runs-on: ubuntu-latest
    steps:
      - uses: eazrael/armbian-build-artillery-x4@github-build 
        with:
          armbian_token:     "${{ secrets.GITHUB_TOKEN }}"  # GitHub token
          armbian_release:   "bookworm"                        # userspace
          armbian_target:    "build"                        # build=image, kernel=kernel
          armbian_board:     "artilleryx4-emmc"                   # build target
  